### ISSUE TITLE
Posts on public groups don't show on members profile and main feed

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2981]
## What's happened?

When I, as admin of a group, post on my public group the feed of that post doesn't show on my profile nither on the main feed for me and all members of my network. It only shows to members of the group. I understand that this should work like this for private and hidden groups, but on public groups, the content should be shared on all feeds and visible to all.

When I set my group to public the phrase says: "Anyone can see the group, its members and their posts."

So, if anyone can see everything, why the feeds from posts inside of that group are not visible to all in the main feed and profile feed?

Is this a bug?

Same thing for pages. If I set on my pages permissions that all content I publish should be public, then the feed generated inside the page should also show on all feeds to everyone. Only if I set the permissions of my content to be seen only by members of the page, only then that posts should show on feeds only for members of the page.

Because of this my groups and pages are now dead. The owner of the groups started to use their profiles to share posts because doing so the posts show on the main feed when inside their public groups the posts are only visible to members of the group and not to all.

So, please, if this is not a bug, change this. The posts on Pages that have the permissions to all should show on main feed to all, and groups that are public should also show the posts of the group on the main feed to all.

Regards

**UPDATE:** I manage to make this to work for me the way I want by editing both on pages and groups app the file module_getcomponent_start 2.php inside the hooks folder and removing the code that is there. But this is not a solution, because now all posts from groups show on the feed to all, when only the posts from **public** groups should show to all. You need to fix this.

## phpFox version
4.8.3

**Comment by harrison05** [comment]
Hi @turha71 

When you post a feed in Public Group or Page, it will shows on main feed and profile feed. This is current workflow of those apps. You can test this feature on our demo site: https://v4.phpfox.com/ . It's working well.

Regards.

**Comment by spirogg** [comment]
@harrison05 in version 4.8.3 this is not working as you say on your demo? 

I created 3 different groups as an admin > 1 for each
public and posted a message
closed and posted a message
private and posted a message

when I posted something to public group in public group feed then I login as registered user and registered user is friend or not friends with admin> it does not show anything on the main feed or the admin's user feed. who posted in the group feed.

so if you are saying that as admin I can post in a public group or page it should display in main feed and my user feed for any registered user that is friends or not friends with me, then this is not working in version 4.8.3 I did fresh install last night and tested a couple hours ago and this is not working..

@harrison05 try a fresh install - 4.8.3 then create a registered user and then login as admin and create a public group as admin and post something in the group feed. 

- now login as a registered user, you will not see the post in the main feed or on admins user feed. 


Spiro

**Comment by spirogg** [comment]
only if I join the group then it shows on main feed

**Comment by turha71** [comment]
> 
> 
> only if I join the group then it shows on main feed

Yes, that's exactly what is happening. Only after a user become member of the group as the posts show on the main feed and profile feed. If the user is not a member of the group all the posts from that public group will not show on the main feed. This should only happen for the other types of groups, but not on public groups.

**Comment by spirogg** [comment]
@harrison05 do you have any update on this ?

**Comment by harrison05** [comment]
> > only if I join the group then it shows on main feed
> 
> Yes, that's exactly what is happening. Only after a user become member of the group as the posts show on the main feed and profile feed. If the user is not a member of the group all the posts from that public group will not show on the main feed. This should only happen for the other types of groups, but not on public groups.

Yes, feed from a public group only shows for members of it. This is the current workflow of Groups App.

Regards.

**Comment by turha71** [comment]
It seems that even when we are subscribed to the group, we still don't see the feed from the group on the main feed. I have subscribed to a group on my site and the blog the owner posted don't show on the main feed,
