### ISSUE TITLE
After phpfox v4.72 upgrade a user's blog is showing in the pages feed as admin of blog post

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2543]
## What happened?
After phpfox v4.72 a user's blog is showing in the pages feed as an admin blog post even though the page does not have any blog.

## What is expected?
A user's blog post that is not a member of the page should not appear as an admin blog post in the pages feed.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

## Screenshots

![screenshot](https://user-images.githubusercontent.com/19594886/50913236-e457e880-1401-11e9-947c-95dfe589e29a.png)

![screenshot-2](https://user-images.githubusercontent.com/19594886/50913428-59c3b900-1402-11e9-97d2-8990f61f72ac.png)

**Comment by harrison05** [comment]
Could you provide steps to reproduce your issue? I can't reproduce it on my site.

Regards.

**Comment by prepperz** [comment]
I cannot provide steps to reproduce as it is a previously existing blog that was there prior to the 4.72 update. I sent you details of where to look to the red fox account.

**Comment by harrison05** [comment]
It seems to show an incorrect feed owner on Pages, but the owner of this blog is another. It's weird, are you sure this issue only occurs after upgrade to 4.7.2?

**Comment by prepperz** [comment]
I can't say for sure. However, prior  4.7.2 there was a similar issue: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2470

I could just delete the feed and see if there is a reoccurrence at some point if any.

**Comment by harrison05** [comment]
I don't think this issue has the same root cause with #2470 and it was fixed from v4.7.0.
